name: midecalpoints
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  intl_phone_field: ^3.2.0
  http: ^1.2.2
  flutter_svg: ^2.0.14
  flutter_map: ^7.0.2
  location: ^6.0.2
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  carousel_slider: ^5.0.0
  onesignal_flutter: ^5.2.7
  quran: ^1.3.1
  flutter_qiblah: ^3.0.4
  geolocator: ^13.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo.ttf
  assets:
    - assets/images/
    - assets/icons/
