import 'package:get/get.dart';

class Languages extends Translations {
  static bool isRTL(String languageCode) {
    const rtlLanguages = {'ar', 'fa', 'ku', 'tk'};
    return rtlLanguages.contains(languageCode);
  }

  @override
  Map<String, Map<String, String>> get keys => {

    'ar': {
      // العربية
      'login': 'تسجيل الدخول',
      'welcome_back': 'مرحبا بعودتك! نحن سعداء بعودتك مرة أخرى. يرجى إدخال بياناتك لتسجيل الدخول إلى حسابك',
      'phone_number': 'رقم الهاتف',
      'password': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة السر؟',
      'no_account': 'ليس لدي حساب، إنشاء حساب الآن',
      'enter': 'الدخول',
      'error': 'خطأ',
      'success': 'نجاح',
      'enter_phone_password': 'يرجى إدخال رقم الهاتف وكلمة المرور',
      'login_success': 'تم تسجيل الدخول بنجاح',
      'login_failed': 'فشل تسجيل الدخول',
      'server_error': 'فشل الاتصال بالخادم',
      'unexpected_error': 'حدث خطأ غير متوقع',

      'crowd_medicine': 'طب الحشود',
      'crowd_medicine_desc':
      'تقدم ميزة الرعاية الصحية للزائرين في ذلك خدمات طبية متخصصة تهدف إلى تلبية احتياجات الزوار اثناء رحلتهم',
      'medical_consultation': 'ميزة الاستشارة الطبية',
      'medical_consultation_desc':
      'تتيح ميزة الاستشارة الطبية للزائرين التواصل مع الأطباء عن بعد للحصول على نصائح صحية و استشارات متخصصة في مختلف المجالات الطبية',
      'medical_centers': 'المراكز الطبية و المستشفيات القريبة',
      'medical_centers_desc':
      'التعرف على أقرب المراكز الصحية عبر خريطة تفاعلية مع معلومات تفصيلية حول الخدمات المقدمة وأرقام التواصل',
      'skip': 'تخطي',
      'next': 'التالي',
      'start_now': 'ابدأ الآن',
      'language': 'العربية',
      'new_registration': 'تسجيل جديد',
      'create_account_easily': 'أنشئ حسابك بسهولة من خلال ملء بياناتك الكاملة',
      'personal_info': 'معلومات شخصية',
      'contact_info': 'معلومات الاتصال',
      'medical_info': 'معلومات طبية',
      'emergency_contact': 'معلومات شخص مقرب',
      'finish': 'إنهاء',
      'registration_success': 'تم إنشاء الحساب بنجاح',
      'fill_required_fields': 'يرجى ملء الحقول المطلوبة',
      'username': 'اسم المستخدم',
      'invalid_phone': 'رقم هاتف غير صالح',
      'email': 'البريد الإلكتروني',
      'enter_password': 'أدخل كلمة المرور',
      'first_name': 'الاسم الأول',
      'middle_name': 'الاسم الأوسط',
      'last_name': 'الاسم الأخير',
      'choose_country': 'اختر البلد من هنا',
      'country': 'البلد',
      'birth_date': 'تاريخ الميلاد',
      'day': 'اليوم',
      'month': 'الشهر',
      'year': 'السنة',
      'gender': 'الجنس',
      'blood_type': 'فصيلة الدم',
      'allergies': 'الحساسية',
      'chronic_diseases': 'الامراض المزمنة',
      'full_name': 'الاسم كامل',
      'province': 'المحافظة',
      'district': 'المحلة',
      'alley': 'الزقاق',
      'house': 'الدار',
      'birth_year': 'سنة الميلاد',
      'relationship': 'صلة القرابة',
      'phone_number_relative': 'رقم هاتفه',
      'select_country': 'اختر البلد من هنا',
      'loading_countries': 'جاري تحميل قائمة الدول',
      'countries_error': 'فشل في تحميل قائمة الدول',
      'no_countries': 'لا توجد دول متاحة',
      'emergencyContactPage.title': 'معلومات شخص مقرب',
      'emergencyContactPage.fullName': 'الاسم الكامل',
      'emergencyContactPage.country': 'البلد',
      'emergencyContactPage.selectCountry': 'اختر البلد',
      'emergencyContactPage.province': 'المحافظة',
      'emergencyContactPage.district': 'المحلة',
      'emergencyContactPage.alley': 'الزقاق',
      'emergencyContactPage.house': 'الدار',
      'emergencyContactPage.birthYear': 'سنة الميلاد',
      'emergencyContactPage.relationship': 'صلة القرابة',
      'emergencyContactPage.phoneNumber': 'رقم الهاتف',
      'emergencyContactPage.loadingCountries': 'جاري تحميل قائمة الدول',
      'emergencyContactPage.countriesError': 'فشل في تحميل قائمة الدول',
      'emergencyContactPage.noCountries': 'لا توجد دول متاحة','diagnosisPage.title': 'التشخيص والملاحظات',
      'medicationsPage.title': 'الفحوصات والدواء',
      'medicationsPage.prescribedMedications': 'الأدوية المصروفة لي',


    },

    'fa': {
      // فارسی
      'crowd_medicine': 'پزشکی جمعیت',
      'crowd_medicine_desc':
      'ارائه خدمات مراقبت های بهداشتی به زائران شامل خدمات پزشکی تخصصی برای رفع نیازهای زائران در طول سفر آنها',
      'medical_consultation': 'ویژگی مشاوره پزشکی',
      'medical_consultation_desc':
      'امکان ارتباط از راه دور با پزشکان برای دریافت توصیه های بهداشتی و مشاوره تخصصی در زمینه های مختلف پزشکی',
      'medical_centers': 'مراکز پزشکی و بیمارستان های نزدیک',
      'medical_centers_desc':
      'شناسایی نزدیکترین مراکز بهداشتی از طریق نقشه تعاملی با اطلاعات دقیق در مورد خدمات ارائه شده و شماره های تماس',
      'skip': 'رد کردن',
      'next': 'بعدی',
      'start_now': 'شروع کنید',
      'language': 'فارسی',
      'login': 'ورود به سیستم',
      'welcome_back': 'خوش آمدید! از دیدن مجدد شما خوشحالیم. لطفاً برای ورود به حساب کاربری خود، اطلاعات خود را وارد کنید',
      'phone_number': 'شماره تلفن',
      'password': 'رمز عبور',
      'forgot_password': 'رمز عبور را فراموش کرده‌اید؟',
      'no_account': 'حساب کاربری ندارید؟ همین حالا ثبت نام کنید',
      'enter': 'ورود',
      'error': 'خطا',
      'success': 'موفقیت',
      'enter_phone_password': 'لطفاً شماره تلفن و رمز عبور را وارد کنید',
      'login_success': 'ورود با موفقیت انجام شد',
      'login_failed': 'ورود ناموفق بود',
      'server_error': 'اتصال به سرور ناموفق بود',
      'unexpected_error': 'خطای غیرمنتظره رخ داد',
      'new_registration': 'ثبت نام جدید',
      'create_account_easily': 'با پر کردن اطلاعات کامل خود به راحتی حساب کاربری خود را ایجاد کنید',
      'personal_info': 'اطلاعات شخصی',
      'contact_info': 'اطلاعات تماس',
      'medical_info': 'اطلاعات پزشکی',
      'emergency_contact': 'اطلاعات تماس اضطراری',
      'finish': 'پایان',
      'registration_success': 'حساب کاربری با موفقیت ایجاد شد',
      'fill_required_fields': 'لطفاً فیلدهای الزامی را پر کنید',
      'first_name': 'نام کوچک',
      'middle_name': 'نام پدر',
      'last_name': 'نام خانوادگی',
      'choose_country': 'از اینجا کشور را انتخاب کنید',
      'country': 'کشور',
      'birth_date': 'تاریخ تولد',
      'day': 'روز',
      'month': 'ماه',
      'year': 'سال',
      'gender': 'جنسیت',
      'emergencyContactPage.title': 'اطلاعات شخص نزدیک',
      'emergencyContactPage.fullName': 'نام کامل',
      'emergencyContactPage.country': 'کشور',
      'emergencyContactPage.selectCountry': 'کشور را انتخاب کنید',
      'emergencyContactPage.province': 'استان',
      'emergencyContactPage.district': 'منطقه',
      'emergencyContactPage.alley': 'کوچه',
      'emergencyContactPage.house': 'خانه',
      'emergencyContactPage.birthYear': 'سال تولد',
      'emergencyContactPage.relationship': 'نسبت',
      'emergencyContactPage.phoneNumber': 'شماره تلفن',
      'emergencyContactPage.loadingCountries': 'در حال بارگیری لیست کشورها',
      'emergencyContactPage.countriesError': 'خطا در بارگیری لیست کشورها',
      'emergencyContactPage.noCountries': 'هیچ کشوری موجود نیست',
      'diagnosisPage.title': 'تشخیص و یادداشت‌ها',
      'medicationsPage.title': 'آزمایشات و دارو',
      'medicationsPage.prescribedMedications': 'داروهای تجویز شده',

    },
    'ku': {
      // كوردي
      'crowd_medicine': 'پزیشکی جەماوەر',
      'crowd_medicine_desc':
      'دابینکردنی خزمەتگوزاری تەندروستی بۆ سەردانکەران لەوانە خزمەتگوزاری پزیشکی تایبەت بۆ پڕکردنەوەی پێداویستیەکانی سەردانکەران لە کاتی گەشتەکەیاندا',
      'medical_consultation': 'تایبەتمەندی ڕاوێژکاری پزیشکی',
      'medical_consultation_desc':
      'ڕێگە دەدات بە سەردانکەران پەیوەندی بکەن لەگەڵ پزیشکان لە دوورەوە بۆ وەرگرتنی ئامۆژگاری تەندروستی و ڕاوێژی پسپۆڕی لە بوارە جیاوازەکانی پزیشکیدا',
      'medical_centers': 'نزیکترین ناوەندە پزیشکی و نەخۆشخانەکان',
      'medical_centers_desc':
      'ناسینەوەی نزیکترین ناوەندی تەندروستی لە ڕێگەی نەخشەی کارلێکەرەوە لەگەڵ زانیاری وردەکاری دەربارەی خزمەتگوزاریە پێشکەشکراوەکان و ژمارەکانی پەیوەندیکردن',
      'skip': 'تێپەڕاندن',
      'next': 'دواتر',
      'start_now': 'دەست پێ بکە',
      'language': 'كوردي',
      'login': 'چوونە ژوورەوە',
      'welcome_back': 'بەخێربێیتەوە! دڵخۆشین بە بینینەوەت. تکایە زانیاریەکانت بنووسە بۆ چوونە ژوورەوەی هەژمارەکەت',
      'phone_number': 'ژمارەی تەلەفۆن',
      'password': 'وشەی تێپەڕ',
      'forgot_password': 'وشەی تێپەڕت لەبیرکردووە؟',
      'no_account': 'هەژمارت نییە؟ ئێستا دروستی بکە',
      'enter': 'چوونە ژوورەوە',
      'error': 'هەڵە',
      'success': 'سەرکەوتن',
      'enter_phone_password': 'تکایە ژمارەی تەلەفۆن و وشەی تێپەڕ بنووسە',
      'login_success': 'چوونە ژوورەوە سەرکەوتوو بوو',
      'login_failed': 'چوونە ژوورەوە سەرکەوتوو نەبوو',
      'server_error': 'پەیوەندی بە ڕاژەوە سەرکەوتوو نەبوو',
      'unexpected_error': 'هەڵەیەکی چاوەڕواننەکراو ڕوویدا',
      'new_registration': 'تۆمارکردنی نوێ',
      'create_account_easily': 'به‌ئاسانی هه‌ژماره‌که‌ت دروست بکه‌ له‌ڕێگه‌ی پڕکردنه‌وه‌ی زانیارییه‌ته‌واوه‌کانت',
      'personal_info': 'زانیاری که‌سی',
      'contact_info': 'زانیاری په‌یوه‌ندی',
      'medical_info': 'زانیاری پزیشکی',
      'emergency_contact': 'زانیاری که‌سی نزیک',
      'finish': 'کۆتایی',
      'registration_success': 'هه‌ژمار به‌سه‌رکه‌وتوویی دروست کرا',
      'fill_required_fields': 'تکایه‌ خانه‌ پێویسته‌کان پڕ بکه‌وه',
      'username': 'ناوی بەکارهێنەر',
      'invalid_phone': 'ژمارەی تەلەفۆن نادروستە',
      'email': 'ئیمەیل',
      'enter_password': 'تێپەڕەوشە بنووسە',
      'first_name': 'ناوی پێشوا',
      'middle_name': 'ناوی پەرزگار',
      'last_name': 'ناوی پەیوەند',
      'choose_country': 'بەهەڵ بدەوە بەشەیە بە مەناوە',
      'country': 'بەشە',
      'birth_date': 'ڕۆژ و شەمە',
      'day': 'ڕۆژ',
      'month': 'شەمە',
      'year': 'سال',
      'gender': 'جەنس',
      'blood_type': 'جۆری خوێن',
      'allergies': 'هەستیاری',
      'chronic_diseases': 'نەخۆشییە درێژخایەنەکان',

      // New Emergency Contact Page translations
      'full_name': 'ناوی تەواو',
      'province': 'پارێزگا',
      'district': 'ناوچە',
      'alley': 'کۆڵان',
      'house': 'خانوو',
      'birth_year': 'ساڵی لەدایکبوون',
      'relationship': 'پەیوەندی',
      'phone_number_relative': 'ژمارەی تەلەفۆن',
      'select_country': 'وڵات هەڵبژێرە',
      'loading_countries': 'لیستی وڵاتەکان بارکردن',
      'countries_error': 'هەڵە لە بارکردنی لیستی وڵاتەکان',
      'no_countries': 'هیچ وڵاتێک بەردەست نییە',
      'emergencyContactPage.title': 'زانیاری کەسی نزیک',
      'emergencyContactPage.fullName': 'ناوی تەواو',
      'emergencyContactPage.country': 'وڵات',
      'emergencyContactPage.selectCountry': 'وڵات هەڵبژێرە',
      'emergencyContactPage.province': 'پارێزگا',
      'emergencyContactPage.district': 'ناوچە',
      'emergencyContactPage.alley': 'کۆڵان',
      'emergencyContactPage.house': 'خانوو',
      'emergencyContactPage.birthYear': 'ساڵی لەدایکبوون',
      'emergencyContactPage.relationship': 'پەیوەندی',
      'emergencyContactPage.phoneNumber': 'ژمارەی تەلەفۆن',
      'emergencyContactPage.loadingCountries': 'لیستی وڵاتەکان بارکردن',
      'emergencyContactPage.countriesError': 'هەڵە لە بارکردنی لیستی وڵاتەکان',
      'emergencyContactPage.noCountries': 'هیچ وڵاتێک بەردەست نییە',
      'diagnosisPage.title': 'دەرمانکردن و تێبینییەکان',
      'medicationsPage.title': 'پشکنین و دەرمان',
      'medicationsPage.prescribedMedications': 'دەرمانە دیاریکراوەکان',

    },
    'tk': {
      'crowd_medicine': 'كوتله طبي',
      'crowd_medicine_desc':
      'زیارتچیلر اوچون ساغلیق خذمتلری، زیارتچیلرین سیاحتلری اثناسینده احتیاجلرینی قارشیلاماق اوچون اختصاصلی طبی خذمتلر',
      'medical_consultation': 'طبی مشورت اوزللیغی',
      'medical_consultation_desc':
      'زیارتچیلرین مختلف طبی ساحه‌لرده اختصاصلی مشورت و صحی توصیه‌لر آلماق اوچون دوكتورلر ایله اوزاقدان ارتباط قورماسینی ساغلار',
      'medical_centers': 'یاقین طبی مركزلر و خسته‌خانه‌لر',
      'medical_centers_desc':
      'تقدیم ائدیلن خذمتلر و تماس نمره‌لری حقینده تفصیللی معلومات ایله اینتراكتیو خریطه واسطه‌سیله ان یاقین صحی مركزلری تانیماق',
      'skip': 'كئچ',
      'next': 'سونراكی',
      'start_now': 'ایندی باشلا',
      'language': 'تركماني',
      'login': 'گیریش',
      'welcome_back': 'خوش گلدیڭیز! سیزی یئنه گؤرمکدن خوشحالیق. حسابیڭیزا گیرمک اوچون معلوماتلاریڭیزی داخل ائدین',
      'phone_number': 'تلفن نؤمره‌سی',
      'password': 'شیفره',
      'forgot_password': 'شیفره‌نی اونوتدوڭوز؟',
      'no_account': 'حسابیڭیز یوخدور؟ ایندی یارادین',
      'enter': 'گیریش',
      'error': 'خطا',
      'success': 'باشاریلی',
      'enter_phone_password': 'لطفاً تلفن نؤمره‌سی و شیفره‌نی داخل ائدین',
      'login_success': 'گیریش باشاریلی اولدو',
      'login_failed': 'گیریش باشاریسیز اولدو',
      'server_error': 'سئروئر ایله باغلانتی باشاریسیز اولدو',
      'unexpected_error': 'گؤزلنیلمز خطا باش وئردی',
      'new_registration': 'تازه قئيد',
      'create_account_easily': 'دولی معلوماتلاریڭیزی دولدورماق آرقالی حسابیڭیزی آڭساتلیق بیلن دؤرەدیڭ',
      'personal_info': 'شخصی معلومات',
      'contact_info': 'الاقا معلوماتی',
      'medical_info': 'مدیکال معلومات',
      'emergency_contact': 'یاقین آدامیڭ معلوماتی',
      'finish': 'تامامله',
      'registration_success': 'حساب اوڭاتلیقلی دؤرەدیلدی',
      'fill_required_fields': 'زەرور بؤلوملری دولدوریڭ',
      'username': 'قوللانیجی آدی',
      'invalid_phone': 'گچرسیز تلفن نؤمره‌سی',
      'email': 'ایمیل',
      'enter_password': 'شیفره‌نی داخل ائدین',
      'first_name': 'آد',
      'middle_name': 'آرا آد',
      'last_name': 'آییل آد',
      'choose_country': 'اولکه سئچین',
      'country': 'اولکه',
      'birth_date': 'دوغوم تاریخی',
      'day': 'گون',
      'month': 'آی',
      'year': 'ایل',
      'gender': 'جینسیت',
      'blood_type': 'قان گروهی',
      'allergies': 'آلرژیلر',
      'chronic_diseases': 'خرونیکی خسته‌لیکلر',
      'full_name': 'دولی آد',
      'province': 'ولایت',
      'district': 'اتراپ',
      'alley': 'کؤچه',
      'house': 'اؤی',
      'birth_year': 'دوغلان ییلی',
      'relationship': 'غارینداشلیق',
      'phone_number_relative': 'تلفن بلگیسی',
      'select_country': 'یورت سایلاڭ',
      'loading_countries': 'یورتلاریڭ لیستەسی یوکلەنیأر',
      'countries_error': 'یورتلاریڭ لیستەسینی یوکلەمەک باشارسیز',
      'no_countries': 'هیچ یورت یوق',
      'emergencyContactPage.title': 'یاقین آدامیڭ معلوماتی',
      'emergencyContactPage.fullName': 'دولی آد',
      'emergencyContactPage.country': 'یورت',
      'emergencyContactPage.selectCountry': 'یورت سایلاڭ',
      'emergencyContactPage.province': 'ولایت',
      'emergencyContactPage.district': 'اتراپ',
      'emergencyContactPage.alley': 'کؤچه',
      'emergencyContactPage.house': 'اؤی',
      'emergencyContactPage.birthYear': 'دوغلان ییلی',
      'emergencyContactPage.relationship': 'غارینداشلیق',
      'emergencyContactPage.phoneNumber': 'تلفن بلگیسی',
      'emergencyContactPage.loadingCountries': 'یورتلاریڭ لیستەسی یوکلەنیأر',
      'emergencyContactPage.countriesError': 'یورتلاریڭ لیستەسینی یوکلەمەک باشارسیز',
      'emergencyContactPage.noCountries': 'هیچ یورت یوق',
      'diagnosisPage.title': 'تشخیص و بلگیلر',
      'medicationsPage.title': 'بارلاما و درمانلار',
      'medicationsPage.prescribedMedications': 'یازیلان درمانلار',

    },
    'en': {
      'crowd_medicine': 'Crowd Medicine',
      'crowd_medicine_desc':
      'Providing healthcare services for visitors including specialized medical services aimed at meeting visitors\' needs during their journey',
      'medical_consultation': 'Medical Consultation Feature',
      'medical_consultation_desc':
      'Allows visitors to communicate remotely with doctors to obtain health advice and specialized consultations in various medical fields',
      'medical_centers': 'Nearby Medical Centers and Hospitals',
      'medical_centers_desc':
      'Identify the nearest health centers through an interactive map with detailed information about services provided and contact numbers',
      'skip': 'Skip',
      'next': 'Next',
      'start_now': 'Start Now',
      'language': 'English',
      'login': 'Login',
      'welcome_back': 'Welcome back! We\'re glad to see you again. Please enter your credentials to login to your account',
      'phone_number': 'Phone Number',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'no_account': 'Don\'t have an account? Create one now',
      'enter': 'Enter',
      'error': 'Error',
      'success': 'Success',
      'enter_phone_password': 'Please enter phone number and password',
      'login_success': 'Login successful',
      'login_failed': 'Login failed',
      'server_error': 'Server connection failed',
      'unexpected_error': 'An unexpected error occurred',
      'new_registration': 'New Registration',
      'create_account_easily': 'Create your account easily by filling in your complete information',
      'personal_info': 'Personal Information',
      'contact_info': 'Contact Information',
      'medical_info': 'Medical Information',
      'emergency_contact': 'Emergency Contact',
      'finish': 'Finish',
      'registration_success': 'Account created successfully',
      'fill_required_fields': 'Please fill in the required fields',
      'username': 'Username',
      'invalid_phone': 'Invalid phone number',
      'email': 'Email',
      'enter_password': 'Enter Password',
      'first_name': 'First Name',
      'middle_name': 'Middle Name',
      'last_name': 'Last Name',
      'choose_country': 'Choose country here',
      'country': 'Country',
      'birth_date': 'Birth Date',
      'day': 'Day',
      'month': 'Month',
      'year': 'Year',
      'gender': 'Gender',
      'blood_type': 'گروه خونی',
      'allergies': 'حساسیت‌ها',
      'chronic_diseases': 'بیماری‌های مزمن',

      'full_name': 'نام کامل',
      'province': 'استان',
      'district': 'منطقه',
      'alley': 'کوچه',
      'house': 'خانه',
      'birth_year': 'سال تولد',
      'relationship': 'نسبت',
      'phone_number_relative': 'شماره تلفن',
      'select_country': 'کشور را انتخاب کنید',
      'loading_countries': 'در حال بارگیری لیست کشورها',
      'countries_error': 'خطا در بارگیری لیست کشورها',
      'no_countries': 'هیچ کشوری موجود نیست',
      'emergencyContactPage.title': 'Emergency Contact Information',
      'emergencyContactPage.fullName': 'Full Name',
      'emergencyContactPage.country': 'Country',
      'emergencyContactPage.selectCountry': 'Select Country',
      'emergencyContactPage.province': 'Province',
      'emergencyContactPage.district': 'District',
      'emergencyContactPage.alley': 'Alley',
      'emergencyContactPage.house': 'House',
      'emergencyContactPage.birthYear': 'Birth Year',
      'emergencyContactPage.relationship': 'Relationship',
      'emergencyContactPage.phoneNumber': 'Phone Number',
      'emergencyContactPage.loadingCountries': 'Loading countries list',
      'emergencyContactPage.countriesError': 'Failed to load countries list',
      'emergencyContactPage.noCountries': 'No countries available',
      'diagnosisPage.title': 'Diagnosis & Notes',
      'medicationsPage.title': 'Tests & Medications',
      'medicationsPage.prescribedMedications': 'My Prescribed Medications',
  },
  };

}